// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ABS.Configuration
{
    using ABS.Model;

    // Seat
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class SeatConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Seat>
    {
        public SeatConfiguration()
            : this("dbo")
        {
        }

        public SeatConfiguration(string schema)
        {
            ToTable("Seat", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Row).HasColumnName(@"Row").HasColumnType("int").IsRequired();
            Property(x => x.Column).HasColumnName(@"Column").HasColumnType("int").IsRequired();
            Property(x => x.IsTaken).HasColumnName(@"IsTaken").HasColumnType("bit").IsRequired();
            Property(x => x.FlightSectionId).HasColumnName(@"FlightSectionId").HasColumnType("int").IsRequired();

            // Foreign keys
            HasRequired(a => a.FlightSection).WithMany(b => b.Seats).HasForeignKey(c => c.FlightSectionId).WillCascadeOnDelete(false); // FK__Seat__FlightSect__1ED998B2
        }
    }

}
// </auto-generated>
