// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ABS.Model
{

    // Airport
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class Airport
    {
        public int Id { get; set; } // Id (Primary key)
        public string AirportName { get; set; } // AirportName (length: 3)

        // Reverse navigation

        /// <summary>
        /// Child Flights where [Flight].[DestinationId] point to this entity (FK__Flight__Destinat__182C9B23)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Flight> Destination { get; set; } // Flight.FK__Flight__Destinat__182C9B23
        /// <summary>
        /// Child Flights where [Flight].[OriginId] point to this entity (FK__Flight__OriginId__173876EA)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Flight> Origin { get; set; } // Flight.FK__Flight__OriginId__173876EA

        public Airport()
        {
            Destination = new System.Collections.Generic.List<Flight>();
            Origin = new System.Collections.Generic.List<Flight>();
        }
    }

}
// </auto-generated>
