// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ABS.Model
{

    // FlightSectionType
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class FlightSectionType
    {
        public int Id { get; set; } // Id (Primary key)
        public string FlightSectionName { get; set; } // FlightSectionName (length: 30)

        // Reverse navigation

        /// <summary>
        /// Child FlightSections where [FlightSection].[FlightSectionTypeId] point to this entity (FK__FlightSec__Fligh__1BFD2C07)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<FlightSection> FlightSections { get; set; } // FlightSection.FK__FlightSec__Fligh__1BFD2C07

        public FlightSectionType()
        {
            FlightSections = new System.Collections.Generic.List<FlightSection>();
        }
    }

}
// </auto-generated>
