// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ABS.Model
{

    // FlightSection
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class FlightSection
    {
        public int Id { get; set; } // Id (Primary key)
        public int FlightId { get; set; } // FlightId
        public int FlightSectionTypeId { get; set; } // FlightSectionTypeId

        // Reverse navigation

        /// <summary>
        /// Child Seats where [Seat].[FlightSectionId] point to this entity (FK__Seat__FlightSect__1ED998B2)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Seat> Seats { get; set; } // Seat.FK__Seat__FlightSect__1ED998B2

        // Foreign keys

        /// <summary>
        /// Parent Flight pointed by [FlightSection].([FlightId]) (FK__FlightSec__Fligh__1B0907CE)
        /// </summary>
        public virtual Flight Flight { get; set; } // FK__FlightSec__Fligh__1B0907CE
        /// <summary>
        /// Parent FlightSectionType pointed by [FlightSection].([FlightSectionTypeId]) (FK__FlightSec__Fligh__1BFD2C07)
        /// </summary>
        public virtual FlightSectionType FlightSectionType { get; set; } // FK__FlightSec__Fligh__1BFD2C07

        public FlightSection()
        {
            Seats = new System.Collections.Generic.List<Seat>();
        }
    }

}
// </auto-generated>
