// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ABS.Model
{

    // Seat
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class Seat
    {
        public int Id { get; set; } // Id (Primary key)
        public int Row { get; set; } // Row
        public int Column { get; set; } // Column
        public bool IsTaken { get; set; } // IsTaken
        public int FlightSectionId { get; set; } // FlightSectionId

        // Foreign keys

        /// <summary>
        /// Parent FlightSection pointed by [Seat].([FlightSectionId]) (FK__Seat__FlightSect__1ED998B2)
        /// </summary>
        public virtual FlightSection FlightSection { get; set; } // FK__Seat__FlightSect__1ED998B2
    }

}
// </auto-generated>
